"use client"
import "./globals.css"
import type { Metadata } from "next"
import React from "react"
import { Inter } from "next/font/google"
import AppContextProvider from "@/providers"
import { Navbar } from "@/components/Navbar"

import SideBar from "@/components/sidebar/SideBar"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<AppContextProvider>
					<div>
						<Navbar />
						<SideBar />
					</div>
					<div>{children}</div>
				</AppContextProvider>
			</body>
		</html>
	)
}
